export const NEW_CALL_ACTIONS = {
    JOIN_HUMAN: "JOIN_HUMAN",
    LEAVE_HUMAN: "LEAVE_HUMAN",
    JOIN_SCREEN: "JOIN_SCREEN",
    LEAVE_SCREEN: "LEAVE_SCREEN",
    HIDE_DRAWER: "HIDE_DRAWER",
    SHOW_DRAWER: "SHOW_DRAWER"
};